- name: Dev Station Instalator
  hosts: 127.0.0.1
  connection: local
- import_playbook: playbooks/autostart.yml
- import_playbook: playbooks/caprine.yml
- import_playbook: playbooks/chrome.yml
- import_playbook: playbooks/crypto.yml
- import_playbook: playbooks/deb.yml
- import_playbook: playbooks/docker.yml
- import_playbook: playbooks/dropbox.yml
- import_playbook: playbooks/elementary-os-apps.yml
  when: ansible_distribution_release == 'juno'
- import_playbook: playbooks/elementary-tweaks.yml
  when: ansible_distribution_release == 'juno'
- import_playbook: playbooks/flatpak.yml
- import_playbook: playbooks/fusuma.yml
- import_playbook: playbooks/grub-customizer.yml
- import_playbook: playbooks/idea-shortcuts.yml
- import_playbook: playbooks/java.yml
- import_playbook: playbooks/jetbrains-toolbox.yml
- import_playbook: playbooks/keepassxc.yml
- import_playbook: playbooks/multimedia-codecs.yml
- import_playbook: playbooks/nord-vpn.yml
- import_playbook: playbooks/plank.yml
- import_playbook: playbooks/qnapi.yml
- import_playbook: playbooks/remmina.yml
- import_playbook: playbooks/sdkman.yml
- import_playbook: playbooks/terminal-tools.yml
- import_playbook: playbooks/utilities.yml
- import_playbook: playbooks/unetbootin.yml
- import_playbook: playbooks/vim.yml
- import_playbook: playbooks/virtualbox.yml
- import_playbook: playbooks/vivaldi.yml
- import_playbook: playbooks/wallpapers.yml
  when: ansible_distribution_release == 'juno'
- import_playbook: playbooks/wingpanel-ayatana.yml
  when: ansible_distribution_release == 'juno'
- import_playbook: playbooks/wireshark-installation.yml
- import_playbook: playbooks/yakuake.yml
- import_playbook: playbooks/yubikey.yml
- import_playbook: playbooks/zsh.yml

#Must be on the endd because it causes exception during adding new apt repos
- import_playbook: playbooks/dns-over-https.yml

