- name: Slack
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Install Slack from deb package from Internet
      apt:
        deb: https://downloads.slack-edge.com/linux_releases/slack-desktop-4.0.2-amd64.deb
      tags:
      - slack
      become: true
