- name: Utilities
  hosts: 127.0.0.1
  connection: local
  tasks:

  - name: Add UNetbootin Repository
    apt_repository:
      repo: ppa:gezakovacs/ppa
    become: true

  - name: Install Ubuntu packages
    apt: name="{{packages}}" state=present
    vars:
      packages:
      - cargo
      - python
      - python-pip
      - python3
      - python3-pip
      - file-roller
      - audacity
      - bleachbit
      - dconf-editor
      - baobab
      - gnome-font-viewer
      - gnome-disk-utility
      - gnome-system-monitor
      - gnome-power-manager
      - gnome-tweak-tool
      - gdebi-core
      - gparted
      - htop
      # For network issues debugging
      - iptraf
      - iftop
      - menulibre
      - pinta
      - pulseaudio
      - remmina
      - transmission
      - vlc
      - unetbootin
      - unace
      - sharutils
      - uudeview
      - mpack
      - arj
      - cabextract
      - shutter
    become: true

